export const LEVELS = [
  {
    id: 1,
    name: 'THE YARD',
    arenaSize: { width: 40, depth: 40 },
    skyColor: 0x1a1a2e,
    floorColor: 0x3a3a5c,
    obstacleColor: 0x556688,
    playerSpawn: { x: 0, y: 0, z: -12 },
    obstacles: [
      { type: 'box', pos: [6, 0, 6], size: [2, 3, 2] },
      { type: 'box', pos: [-6, 0, 6], size: [2, 3, 2] },
      { type: 'box', pos: [0, 0, 10], size: [3, 2, 1] },
      { type: 'cylinder', pos: [10, 0, -5], size: [1, 4] },
      { type: 'cylinder', pos: [-10, 0, -5], size: [1, 4] },
      { type: 'box', pos: [8, 0, 8], size: [1.5, 2, 4] },
      { type: 'box', pos: [-8, 0, 8], size: [1.5, 2, 4] },
    ],
    waves: [
      {
        enemies: [{ type: 'grunt', count: 3 }],
        spawnZone: { minX: -10, maxX: 10, minZ: 5, maxZ: 15 },
        delay: 0,
      },
      {
        enemies: [{ type: 'grunt', count: 4 }],
        spawnZone: { minX: -15, maxX: 15, minZ: 5, maxZ: 15 },
        delay: 2,
      },
    ],
  },
  {
    id: 2,
    name: 'THE BLOCK',
    arenaSize: { width: 50, depth: 50 },
    skyColor: 0x0d1117,
    floorColor: 0x2d4a3e,
    obstacleColor: 0x448866,
    playerSpawn: { x: 0, y: 0, z: -18 },
    obstacles: [
      { type: 'box', pos: [0, 0, 0], size: [4, 3, 4] },
      { type: 'box', pos: [10, 0, 10], size: [2, 2.5, 2] },
      { type: 'box', pos: [-10, 0, 10], size: [2, 2.5, 2] },
      { type: 'box', pos: [10, 0, -10], size: [2, 2.5, 2] },
      { type: 'box', pos: [-10, 0, -10], size: [2, 2.5, 2] },
      { type: 'cylinder', pos: [5, 0, 15], size: [1.2, 5] },
      { type: 'cylinder', pos: [-5, 0, 15], size: [1.2, 5] },
      { type: 'box', pos: [15, 0, 0], size: [1.5, 3, 6] },
      { type: 'box', pos: [-15, 0, 0], size: [1.5, 3, 6] },
      { type: 'box', pos: [0, 0, 15], size: [6, 2, 1.5] },
    ],
    waves: [
      {
        enemies: [{ type: 'grunt', count: 4 }, { type: 'fast', count: 2 }],
        spawnZone: { minX: -15, maxX: 15, minZ: 10, maxZ: 20 },
        delay: 0,
      },
      {
        enemies: [{ type: 'grunt', count: 3 }, { type: 'fast', count: 3 }],
        spawnZone: { minX: -20, maxX: 20, minZ: 5, maxZ: 20 },
        delay: 3,
      },
    ],
  },
  {
    id: 3,
    name: 'THE PIT',
    arenaSize: { width: 45, depth: 45 },
    skyColor: 0x1a0a0a,
    floorColor: 0x4a2a2a,
    obstacleColor: 0x884444,
    playerSpawn: { x: 0, y: 0, z: -15 },
    obstacles: [
      // Central structure
      { type: 'box', pos: [0, 0, 0], size: [3, 4, 3] },
      { type: 'box', pos: [3, 0, 3], size: [2, 3, 2] },
      { type: 'box', pos: [-3, 0, 3], size: [2, 3, 2] },
      { type: 'box', pos: [3, 0, -3], size: [2, 3, 2] },
      { type: 'box', pos: [-3, 0, -3], size: [2, 3, 2] },
      // Perimeter cover
      { type: 'box', pos: [12, 0, 0], size: [2, 2.5, 5] },
      { type: 'box', pos: [-12, 0, 0], size: [2, 2.5, 5] },
      { type: 'box', pos: [0, 0, 12], size: [5, 2.5, 2] },
      { type: 'cylinder', pos: [8, 0, 8], size: [1, 4] },
      { type: 'cylinder', pos: [-8, 0, 8], size: [1, 4] },
      { type: 'cylinder', pos: [8, 0, -8], size: [1, 4] },
      { type: 'cylinder', pos: [-8, 0, -8], size: [1, 4] },
    ],
    waves: [
      {
        enemies: [{ type: 'grunt', count: 4 }, { type: 'fast', count: 2 }],
        spawnZone: { minX: -15, maxX: 15, minZ: 5, maxZ: 18 },
        delay: 0,
      },
      {
        enemies: [{ type: 'fast', count: 4 }, { type: 'tank', count: 1 }],
        spawnZone: { minX: -18, maxX: 18, minZ: 5, maxZ: 18 },
        delay: 2,
      },
      {
        enemies: [{ type: 'grunt', count: 3 }, { type: 'fast', count: 2 }, { type: 'tank', count: 1 }],
        spawnZone: { minX: -18, maxX: 18, minZ: -18, maxZ: 18 },
        delay: 3,
      },
    ],
  },
  {
    id: 4,
    name: 'THE MAZE',
    arenaSize: { width: 55, depth: 55 },
    skyColor: 0x0a0a1a,
    floorColor: 0x2a2a4a,
    obstacleColor: 0x5555aa,
    playerSpawn: { x: 0, y: 0, z: -20 },
    obstacles: [
      // Maze-like corridors
      { type: 'box', pos: [0, 0, -5], size: [15, 3, 1.5] },
      { type: 'box', pos: [7, 0, 5], size: [1.5, 3, 10] },
      { type: 'box', pos: [-7, 0, 5], size: [1.5, 3, 10] },
      { type: 'box', pos: [0, 0, 12], size: [10, 3, 1.5] },
      { type: 'box', pos: [14, 0, 12], size: [1.5, 3, 12] },
      { type: 'box', pos: [-14, 0, 12], size: [1.5, 3, 12] },
      { type: 'box', pos: [14, 0, -5], size: [1.5, 3, 8] },
      { type: 'box', pos: [-14, 0, -5], size: [1.5, 3, 8] },
      // Cover blocks
      { type: 'box', pos: [3, 0, 18], size: [2, 2, 2] },
      { type: 'box', pos: [-3, 0, 18], size: [2, 2, 2] },
      { type: 'cylinder', pos: [0, 0, 8], size: [1.5, 4] },
      { type: 'cylinder', pos: [10, 0, 0], size: [1, 3] },
      { type: 'cylinder', pos: [-10, 0, 0], size: [1, 3] },
    ],
    waves: [
      {
        enemies: [{ type: 'grunt', count: 5 }, { type: 'fast', count: 3 }],
        spawnZone: { minX: -20, maxX: 20, minZ: 10, maxZ: 22 },
        delay: 0,
      },
      {
        enemies: [{ type: 'fast', count: 4 }, { type: 'tank', count: 2 }],
        spawnZone: { minX: -22, maxX: 22, minZ: 10, maxZ: 22 },
        delay: 2,
      },
      {
        enemies: [{ type: 'grunt', count: 4 }, { type: 'fast', count: 3 }, { type: 'tank', count: 2 }],
        spawnZone: { minX: -22, maxX: 22, minZ: -22, maxZ: 22 },
        delay: 3,
      },
    ],
  },
  {
    id: 5,
    name: 'THE GAUNTLET',
    arenaSize: { width: 60, depth: 60 },
    skyColor: 0x0a0005,
    floorColor: 0x3a1a2a,
    obstacleColor: 0xaa4466,
    playerSpawn: { x: 0, y: 0, z: -22 },
    obstacles: [
      // Heavy cover — final arena
      { type: 'box', pos: [0, 0, 0], size: [5, 4, 5] },
      { type: 'box', pos: [12, 0, 0], size: [3, 3, 3] },
      { type: 'box', pos: [-12, 0, 0], size: [3, 3, 3] },
      { type: 'box', pos: [0, 0, 12], size: [3, 3, 3] },
      { type: 'box', pos: [0, 0, -12], size: [3, 3, 3] },
      { type: 'box', pos: [8, 0, 15], size: [2, 2.5, 6] },
      { type: 'box', pos: [-8, 0, 15], size: [2, 2.5, 6] },
      { type: 'box', pos: [8, 0, -8], size: [2, 2.5, 6] },
      { type: 'box', pos: [-8, 0, -8], size: [2, 2.5, 6] },
      { type: 'cylinder', pos: [18, 0, 10], size: [1.5, 5] },
      { type: 'cylinder', pos: [-18, 0, 10], size: [1.5, 5] },
      { type: 'cylinder', pos: [18, 0, -10], size: [1.5, 5] },
      { type: 'cylinder', pos: [-18, 0, -10], size: [1.5, 5] },
      { type: 'box', pos: [20, 0, 0], size: [1.5, 3, 8] },
      { type: 'box', pos: [-20, 0, 0], size: [1.5, 3, 8] },
    ],
    waves: [
      {
        enemies: [{ type: 'grunt', count: 5 }, { type: 'fast', count: 3 }, { type: 'tank', count: 1 }],
        spawnZone: { minX: -20, maxX: 20, minZ: 10, maxZ: 25 },
        delay: 0,
      },
      {
        enemies: [{ type: 'fast', count: 5 }, { type: 'tank', count: 2 }],
        spawnZone: { minX: -25, maxX: 25, minZ: 10, maxZ: 25 },
        delay: 2,
      },
      {
        enemies: [{ type: 'grunt', count: 4 }, { type: 'fast', count: 4 }, { type: 'tank', count: 2 }],
        spawnZone: { minX: -25, maxX: 25, minZ: -25, maxZ: 25 },
        delay: 2,
      },
      {
        enemies: [{ type: 'tank', count: 4 }, { type: 'fast', count: 6 }],
        spawnZone: { minX: -25, maxX: 25, minZ: -25, maxZ: 25 },
        delay: 3,
      },
    ],
  },
];
